/**
 * Export: Markdown and PDF.
 *
 * Both formats are built from the same content and stamped with the same
 * version.json values, so an exported file always says exactly which build
 * produced it.
 *
 * A note on PDF text encoding, because it bites silently:
 * pdfkit's built-in fonts use WinAnsi encoding. Characters outside it are not
 * rejected — they are silently rendered as mojibake (Devanagari "साई राम"
 * comes out as garbage punctuation). Emitting a corrupted document with no
 * warning is worse than refusing, so unsupported characters are replaced with a
 * visible marker and the PDF says so, pointing at the Markdown export, which is
 * UTF-8 and lossless.
 */

import PDFDocument from "pdfkit";
import { readVersion } from "../config/env.js";

/** Characters WinAnsi adds above Latin-1, so they are safe in a PDF. */
const WINANSI_EXTRAS = new Set(
  "€‚ƒ„…†‡ˆ‰Š‹ŒŽ" +
    "‘’“”•–—˜™š›œžŸ",
);

/** Replaces a run of unsupported characters; visible, not silent. */
const PDF_PLACEHOLDER = "¿"; // inverted question mark — clearly not content

/**
 * @param {string} char
 * @returns {boolean}
 */
function isPdfSafeChar(char) {
  const code = char.codePointAt(0);
  if (code === 0x0a || code === 0x09) return true;
  if (code < 0x20) return false;
  if (code <= 0xff) return true;
  return WINANSI_EXTRAS.has(char);
}

/**
 * Makes a string safe to draw with a built-in PDF font.
 *
 * @param {string} text
 * @returns {{ text: string, replaced: number }}
 */
export function toPdfSafe(text) {
  const input = String(text ?? "");
  let output = "";
  let replaced = 0;
  let inRun = false;

  for (const char of input) {
    if (isPdfSafeChar(char)) {
      output += char;
      inRun = false;
      continue;
    }
    replaced += 1;
    // Collapse a run of unsupported characters into one marker so a whole
    // sentence of another script does not become a wall of markers.
    if (!inRun) {
      output += PDF_PLACEHOLDER;
      inRun = true;
    }
  }

  return { text: output, replaced };
}

/**
 * A filesystem-safe download filename derived from the meeting title.
 *
 * @param {{ title: string, startedAt?: string | null }} meeting
 * @param {"md" | "pdf"} extension
 */
export function exportFilename(meeting, extension) {
  const base = String(meeting.title ?? "meeting")
    .normalize("NFKD")
    .replace(/[^\w\s-]/g, "")
    .trim()
    .replace(/\s+/g, "-")
    .slice(0, 60)
    .replace(/^-+|-+$/g, "");

  const date = meeting.startedAt ? String(meeting.startedAt).slice(0, 10) : "";
  const stem = [base || "meeting", date].filter(Boolean).join("-");
  return `${stem}.${extension}`;
}

/** The stamp both formats carry. */
export function buildStamp(version = readVersion()) {
  return `Generated by ${version.name} v${version.version} · ${version.releaseDate}`;
}

function formatDate(iso) {
  if (!iso) return "Unknown";
  const date = new Date(iso);
  return Number.isNaN(date.getTime()) ? "Unknown" : date.toISOString().replace("T", " ").slice(0, 16) + " UTC";
}

function formatDuration(startedAt, endedAt) {
  if (!startedAt || !endedAt) return null;
  const ms = new Date(endedAt).getTime() - new Date(startedAt).getTime();
  if (!Number.isFinite(ms) || ms < 0) return null;
  const total = Math.round(ms / 1000);
  return `${Math.floor(total / 60)}m ${total % 60}s`;
}

/**
 * @typedef {Object} ExportInput
 * @property {{ id: string, title: string, startedAt: string, endedAt: string | null, status: string }} meeting
 * @property {{ speakerLabel: string, text: string, sequence: number }[]} transcript
 * @property {(import("../ai/provider.js").MinutesResult & { generated_at?: string }) | null} minutes
 * @property {{ name: string, version: string, releaseDate: string }} [version]
 */

/**
 * Markdown export. UTF-8 and lossless — the format to reach for when the
 * transcript contains scripts a built-in PDF font cannot draw.
 *
 * @param {ExportInput} input
 * @returns {string}
 */
export function buildMarkdown({ meeting, transcript, minutes, version }) {
  const stamp = buildStamp(version);
  const duration = formatDuration(meeting.startedAt, meeting.endedAt);
  const lines = [];

  lines.push(`# ${meeting.title}`, "");
  lines.push(`- **Started:** ${formatDate(meeting.startedAt)}`);
  if (meeting.endedAt) lines.push(`- **Ended:** ${formatDate(meeting.endedAt)}`);
  if (duration) lines.push(`- **Duration:** ${duration}`);
  lines.push(`- **Status:** ${meeting.status}`);
  lines.push("");

  lines.push("## Minutes", "");

  if (!minutes) {
    lines.push(
      meeting.status === "failed"
        ? "_Minutes could not be generated for this meeting. The transcript below was still captured._"
        : "_No minutes have been generated for this meeting yet._",
      "",
    );
  } else {
    lines.push("### Decisions", "");
    lines.push(
      minutes.decisions.length === 0
        ? "_No decisions were recorded in this meeting._"
        : minutes.decisions.map((d) => `- ${d}`).join("\n"),
      "",
    );

    lines.push("### Action items", "");
    if (minutes.action_items.length === 0) {
      lines.push("_Nobody committed to anything in this meeting._", "");
    } else {
      lines.push("| Task | Owner | Due |", "| --- | --- | --- |");
      for (const item of minutes.action_items) {
        // Escape pipes so a task containing one cannot break the table.
        const cell = (value) => String(value ?? "").replace(/\|/g, "\\|");
        lines.push(`| ${cell(item.task)} | ${cell(item.owner)} | ${cell(item.due)} |`);
      }
      lines.push("");
    }

    lines.push("### Open questions", "");
    lines.push(
      minutes.open_questions.length === 0
        ? "_Nothing was left unresolved._"
        : minutes.open_questions.map((q) => `- ${q}`).join("\n"),
      "",
    );
  }

  lines.push("## Transcript", "");
  if (transcript.length === 0) {
    lines.push("_No speech was transcribed for this meeting._", "");
  } else {
    for (const line of transcript) lines.push(`**${line.speakerLabel}:** ${line.text}`, "");
  }

  lines.push(
    "---",
    "",
    "_Speaker labels are inferred from pauses in the audio, not voice recognition, so they may be wrong._",
    "",
    `_${stamp}_`,
    "",
  );

  return lines.join("\n");
}

/**
 * PDF export.
 *
 * Buffered rather than streamed so a generation failure surfaces before any
 * bytes are sent, which lets the route return a proper error instead of a
 * truncated download.
 *
 * @param {ExportInput} input
 * @param {{ compress?: boolean }} [options]
 *   compress:false leaves content streams readable, which lets tests assert on
 *   the text actually drawn rather than trusting that it was.
 * @returns {Promise<Buffer>}
 */
export function buildPdf({ meeting, transcript, minutes, version }, options = {}) {
  return new Promise((resolve, reject) => {
    const stamp = buildStamp(version);
    let replacedTotal = 0;

    /** Draws text, tracking anything the font cannot represent. */
    const safe = (value) => {
      const { text, replaced } = toPdfSafe(value);
      replacedTotal += replaced;
      return text;
    };

    const doc = new PDFDocument({
      margin: 56,
      compress: options.compress !== false,
      info: {
        Title: safe(meeting.title),
        Creator: `${version?.name ?? "Minutely"} v${version?.version ?? ""}`,
      },
    });

    /** @type {Buffer[]} */
    const chunks = [];
    doc.on("data", (chunk) => chunks.push(chunk));
    doc.on("error", reject);
    doc.on("end", () => resolve(Buffer.concat(chunks)));

    const heading = (text, size = 13) =>
      doc.moveDown(0.8).font("Helvetica-Bold").fontSize(size).fillColor("#111111").text(safe(text));
    const body = (text, options = {}) =>
      doc.font("Helvetica").fontSize(10.5).fillColor("#222222").text(safe(text), options);
    const muted = (text, options = {}) =>
      doc.font("Helvetica-Oblique").fontSize(9.5).fillColor("#666666").text(safe(text), options);

    try {
      // --- Header ---
      doc.font("Helvetica-Bold").fontSize(20).fillColor("#111111").text(safe(meeting.title));

      const duration = formatDuration(meeting.startedAt, meeting.endedAt);
      const meta = [
        formatDate(meeting.startedAt),
        duration,
        `status: ${meeting.status}`,
      ].filter(Boolean);
      doc.moveDown(0.25);
      muted(meta.join("  ·  "));

      // --- Minutes ---
      heading("Minutes", 15);

      if (!minutes) {
        doc.moveDown(0.3);
        muted(
          meeting.status === "failed"
            ? "Minutes could not be generated for this meeting. The transcript below was still captured."
            : "No minutes have been generated for this meeting yet.",
        );
      } else {
        heading("Decisions");
        if (minutes.decisions.length === 0) muted("No decisions were recorded in this meeting.");
        else for (const decision of minutes.decisions) body(`•  ${decision}`, { indent: 6 });

        heading("Action items");
        if (minutes.action_items.length === 0) {
          muted("Nobody committed to anything in this meeting.");
        } else {
          for (const item of minutes.action_items) {
            doc.moveDown(0.35);
            doc.font("Helvetica-Bold").fontSize(10.5).fillColor("#111111").text(safe(item.task), { indent: 6 });
            muted(`Owner: ${item.owner}    Due: ${item.due}`, { indent: 6 });
          }
        }

        heading("Open questions");
        if (minutes.open_questions.length === 0) muted("Nothing was left unresolved.");
        else for (const question of minutes.open_questions) body(`•  ${question}`, { indent: 6 });
      }

      // --- Transcript ---
      heading("Transcript", 15);

      if (transcript.length === 0) {
        doc.moveDown(0.3);
        muted("No speech was transcribed for this meeting.");
      } else {
        for (const line of transcript) {
          doc.moveDown(0.4);
          doc.font("Helvetica-Bold").fontSize(9.5).fillColor("#3b5bdb").text(safe(line.speakerLabel));
          body(line.text);
        }
      }

      // --- Footer ---
      doc.moveDown(1.2);
      doc
        .strokeColor("#dddddd")
        .lineWidth(0.5)
        .moveTo(doc.page.margins.left, doc.y)
        .lineTo(doc.page.width - doc.page.margins.right, doc.y)
        .stroke();
      doc.moveDown(0.6);

      muted(
        "Speaker labels are inferred from pauses in the audio, not voice recognition, so they may be wrong.",
      );

      if (replacedTotal > 0) {
        doc.moveDown(0.3);
        doc
          .font("Helvetica-Oblique")
          .fontSize(9.5)
          .fillColor("#b42318")
          .text(
            `Note: ${replacedTotal} character${replacedTotal === 1 ? "" : "s"} could not be displayed in this PDF and ` +
              `${replacedTotal === 1 ? "was" : "were"} replaced with "${PDF_PLACEHOLDER}". ` +
              `Export as Markdown for the complete text.`,
          );
      }

      doc.moveDown(0.4);
      muted(stamp);

      doc.end();
    } catch (err) {
      reject(err);
    }
  });
}
