/**
 * Export endpoints: headers, content types, and download filenames.
 */

import { describe, it, expect, beforeAll, afterAll, beforeEach } from "vitest";
import request from "supertest";
import { randomUUID } from "node:crypto";
import { readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { createApp } from "../src/app.js";
import { migrate } from "../src/services/migrate.js";
import {
  closeClient,
  createMeeting,
  insertTranscriptLine,
  updateMeetingStatus,
  upsertMinutes,
} from "../src/services/db.js";
import { createFakeProvider } from "./helpers/fakeProvider.js";

const REPO_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..", "..");
const version = JSON.parse(readFileSync(resolve(REPO_ROOT, "version.json"), "utf8"));

let app;
let meetingId;

beforeAll(async () => {
  await migrate({ logger: { info: () => {} } });
  app = createApp({ provider: createFakeProvider() });
});

afterAll(() => {
  closeClient();
});

beforeEach(async () => {
  meetingId = randomUUID();
  await createMeeting({
    id: meetingId,
    title: "Billing rewrite sync",
    startedAt: "2026-08-27T09:30:00Z",
  });
  await insertTranscriptLine({
    meetingId,
    speakerLabel: "Speaker 1",
    text: "we should ship on Friday",
    sequence: 0,
  });
  await upsertMinutes(meetingId, {
    decisions: ["Ship on Friday"],
    action_items: [{ task: "Run the migration", owner: "Priya", due: "Thursday" }],
    open_questions: [],
  });
  await updateMeetingStatus(meetingId, "done", { endedAt: "2026-08-27T09:44:00Z" });
});

describe("GET /api/meetings/:id/export.md", () => {
  it("returns Markdown with the version stamp", async () => {
    const res = await request(app).get(`/api/meetings/${meetingId}/export.md`);

    expect(res.status).toBe(200);
    expect(res.headers["content-type"]).toContain("text/markdown");
    expect(res.headers["content-type"]).toContain("charset=utf-8");
    expect(res.text).toContain("# Billing rewrite sync");
    expect(res.text).toContain(`Generated by ${version.name} v${version.version}`);
    expect(res.text).toContain(version.releaseDate);
  });

  it("offers it as a download with a filename derived from the title", async () => {
    const res = await request(app).get(`/api/meetings/${meetingId}/export.md`);

    expect(res.headers["content-disposition"]).toContain("attachment");
    expect(res.headers["content-disposition"]).toContain(
      "Billing-rewrite-sync-2026-08-27.md",
    );
  });

  it("is not cached, since it reflects live data", async () => {
    const res = await request(app).get(`/api/meetings/${meetingId}/export.md`);
    expect(res.headers["cache-control"]).toContain("no-store");
  });

  it("exports a failed meeting's transcript rather than refusing", async () => {
    const failed = randomUUID();
    await createMeeting({ id: failed, title: "Failed one" });
    await insertTranscriptLine({
      meetingId: failed,
      speakerLabel: "Speaker 1",
      text: "captured anyway",
      sequence: 0,
    });
    await updateMeetingStatus(failed, "failed");

    const res = await request(app).get(`/api/meetings/${failed}/export.md`);

    expect(res.status).toBe(200);
    expect(res.text).toContain("captured anyway");
    expect(res.text).toContain("could not be generated");
  });

  it("404s for a meeting that does not exist", async () => {
    const res = await request(app).get(`/api/meetings/${randomUUID()}/export.md`);
    expect(res.status).toBe(404);
  });

  it("400s on a non-UUID id", async () => {
    const res = await request(app).get("/api/meetings/nope/export.md");
    expect(res.status).toBe(400);
  });
});

describe("GET /api/meetings/:id/export.pdf", () => {
  it("returns a valid PDF", async () => {
    const res = await request(app)
      .get(`/api/meetings/${meetingId}/export.pdf`)
      .buffer()
      .parse((response, callback) => {
        const chunks = [];
        response.on("data", (chunk) => chunks.push(chunk));
        response.on("end", () => callback(null, Buffer.concat(chunks)));
      });

    expect(res.status).toBe(200);
    expect(res.headers["content-type"]).toContain("application/pdf");
    expect(res.body.subarray(0, 5).toString()).toBe("%PDF-");
  });

  it("sets a content length, so the browser can show download progress", async () => {
    const res = await request(app).get(`/api/meetings/${meetingId}/export.pdf`);
    expect(Number(res.headers["content-length"])).toBeGreaterThan(1000);
  });

  it("offers it as a download with a .pdf filename", async () => {
    const res = await request(app).get(`/api/meetings/${meetingId}/export.pdf`);

    expect(res.headers["content-disposition"]).toContain("attachment");
    expect(res.headers["content-disposition"]).toContain(
      "Billing-rewrite-sync-2026-08-27.pdf",
    );
  });

  it("sends a UTF-8 filename alongside an ASCII fallback", async () => {
    const unicode = randomUUID();
    await createMeeting({ id: unicode, title: "Café review", startedAt: "2026-08-27T09:00:00Z" });

    const res = await request(app).get(`/api/meetings/${unicode}/export.pdf`);
    const disposition = res.headers["content-disposition"];

    expect(disposition).toMatch(/filename="[\x20-\x7e]+"/);
    expect(disposition).toContain("filename*=UTF-8''");
  });

  it("404s for a meeting that does not exist", async () => {
    const res = await request(app).get(`/api/meetings/${randomUUID()}/export.pdf`);
    expect(res.status).toBe(404);
  });
});
