/**
 * Export content.
 *
 * The version stamp is the point of most of this: an exported file must always
 * say exactly which build produced it, from the same version.json everything
 * else derives from.
 */

import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import {
  buildMarkdown,
  buildPdf,
  buildStamp,
  exportFilename,
  toPdfSafe,
} from "../src/services/export.js";

const REPO_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..", "..");

/**
 * Extracts the text actually DRAWN into an uncompressed PDF's content streams.
 *
 * pdfkit writes glyphs as hex strings inside `[<hex> kern <hex>] TJ` operators,
 * so a plain substring search over the file only ever matches the /Info
 * metadata dictionary — which is how an earlier version of these tests passed
 * without the footer stamp being rendered at all.
 *
 * @param {Buffer} pdf
 * @returns {string}
 */
function extractPdfText(pdf) {
  const raw = pdf.toString("latin1");
  let text = "";

  for (const match of raw.matchAll(/\[((?:\s*<[0-9a-fA-F]*>\s*-?[\d.]*)+)\]\s*TJ/g)) {
    for (const hexMatch of match[1].matchAll(/<([0-9a-fA-F]*)>/g)) {
      const hex = hexMatch[1];
      for (let i = 0; i + 1 < hex.length; i += 2) {
        text += String.fromCharCode(parseInt(hex.slice(i, i + 2), 16));
      }
    }
    text += "\n";
  }

  return text;
}
const version = JSON.parse(readFileSync(resolve(REPO_ROOT, "version.json"), "utf8"));

const INPUT = {
  meeting: {
    id: "abc",
    title: "Billing rewrite sync",
    startedAt: "2026-08-27T09:30:00Z",
    endedAt: "2026-08-27T09:44:00Z",
    status: "done",
  },
  transcript: [
    { speakerLabel: "Speaker 1", text: "we should ship on Friday", sequence: 0 },
    { speakerLabel: "Priya", text: "I will run the migration", sequence: 1 },
  ],
  minutes: {
    decisions: ["Ship the billing rewrite on Friday"],
    action_items: [{ task: "Run the migration", owner: "Priya", due: "Thursday" }],
    open_questions: ["Do we grandfather existing pricing?"],
    generated_at: "2026-08-27T09:45:00Z",
  },
  version,
};

describe("buildStamp", () => {
  it("uses version.json, the single source of truth", () => {
    expect(buildStamp(version)).toBe(
      `Generated by ${version.name} v${version.version} · ${version.releaseDate}`,
    );
  });

  it("reads version.json directly when not given one", () => {
    expect(buildStamp()).toContain(version.version);
  });
});

describe("buildMarkdown", () => {
  it("carries the version stamp", () => {
    expect(buildMarkdown(INPUT)).toContain(buildStamp(version));
  });

  it("includes the title and metadata", () => {
    const md = buildMarkdown(INPUT);
    expect(md).toContain("# Billing rewrite sync");
    expect(md).toContain("**Duration:** 14m 0s");
    expect(md).toContain("**Status:** done");
  });

  it("renders all three minutes sections", () => {
    const md = buildMarkdown(INPUT);
    expect(md).toContain("### Decisions");
    expect(md).toContain("- Ship the billing rewrite on Friday");
    expect(md).toContain("### Action items");
    expect(md).toContain("| Run the migration | Priya | Thursday |");
    expect(md).toContain("### Open questions");
  });

  it("renders the transcript with speakers", () => {
    const md = buildMarkdown(INPUT);
    expect(md).toContain("**Speaker 1:** we should ship on Friday");
    expect(md).toContain("**Priya:** I will run the migration");
  });

  it("escapes pipes so a task cannot break the table", () => {
    const md = buildMarkdown({
      ...INPUT,
      minutes: {
        ...INPUT.minutes,
        action_items: [{ task: "Fix a | b parsing", owner: "Alex", due: "Friday" }],
      },
    });
    expect(md).toContain("Fix a \\| b parsing");
  });

  it("explains an empty section rather than leaving it blank", () => {
    const md = buildMarkdown({
      ...INPUT,
      minutes: { decisions: [], action_items: [], open_questions: [] },
    });
    expect(md).toContain("_No decisions were recorded in this meeting._");
    expect(md).toContain("_Nobody committed to anything in this meeting._");
  });

  it("says so when minutes failed, and still includes the transcript", () => {
    const md = buildMarkdown({
      ...INPUT,
      meeting: { ...INPUT.meeting, status: "failed" },
      minutes: null,
    });
    expect(md).toContain("could not be generated");
    expect(md).toContain("we should ship on Friday");
  });

  it("handles a meeting with no transcript", () => {
    const md = buildMarkdown({ ...INPUT, transcript: [], minutes: null });
    expect(md).toContain("_No speech was transcribed for this meeting._");
  });

  it("states the speaker-label limitation", () => {
    expect(buildMarkdown(INPUT)).toContain("not voice recognition");
  });

  it("is lossless for non-Latin text, unlike the PDF", () => {
    const md = buildMarkdown({
      ...INPUT,
      transcript: [{ speakerLabel: "साई राम", text: "会議を始めましょう", sequence: 0 }],
    });
    expect(md).toContain("साई राम");
    expect(md).toContain("会議を始めましょう");
  });
});

describe("toPdfSafe", () => {
  it("leaves ASCII untouched", () => {
    expect(toPdfSafe("Ship on Friday")).toEqual({ text: "Ship on Friday", replaced: 0 });
  });

  it("keeps Latin-1 accents, which WinAnsi supports", () => {
    expect(toPdfSafe("Café résumé").replaced).toBe(0);
  });

  it("keeps the WinAnsi extras: curly quotes, dashes, the middle dot", () => {
    expect(toPdfSafe("“don’t” — really").replaced).toBe(0);
    expect(toPdfSafe("Minutely v1.0.0 · 2026-08-27").replaced).toBe(0);
  });

  it("replaces characters the font cannot draw instead of emitting mojibake", () => {
    // Silently rendering these as garbage punctuation is worse than a visible marker.
    const result = toPdfSafe("साई राम");
    expect(result.replaced).toBeGreaterThan(0);
    expect(result.text).not.toContain("साई");
    expect(result.text).toContain("¿");
  });

  it("collapses a run of unsupported characters into one marker", () => {
    const result = toPdfSafe("会議議事録");
    // One marker for the whole run, not one per character.
    expect(result.text).toBe("¿");
    expect(result.replaced).toBe(5);
  });

  it("preserves supported text around an unsupported run", () => {
    expect(toPdfSafe("Owner: साई (lead)").text).toBe("Owner: ¿ (lead)");
  });

  it("keeps newlines and tabs", () => {
    expect(toPdfSafe("a\nb\tc").replaced).toBe(0);
  });
});

describe("exportFilename", () => {
  it("derives a safe name from the title and date", () => {
    expect(exportFilename(INPUT.meeting, "md")).toBe("Billing-rewrite-sync-2026-08-27.md");
  });

  it("strips characters that are awkward in a filename", () => {
    const name = exportFilename({ title: 'Q3: "review" / plan*', startedAt: "2026-08-27T00:00:00Z" }, "pdf");
    expect(name).toBe("Q3-review-plan-2026-08-27.pdf");
    expect(name).not.toMatch(/[/*"?<>|:]/);
  });

  it("falls back when a title reduces to nothing", () => {
    expect(exportFilename({ title: "会議", startedAt: "2026-08-27T00:00:00Z" }, "md")).toBe(
      "meeting-2026-08-27.md",
    );
  });

  it("bounds the length", () => {
    const name = exportFilename({ title: "x".repeat(300), startedAt: "2026-08-27T00:00:00Z" }, "pdf");
    expect(name.length).toBeLessThan(90);
  });
});

describe("buildPdf", () => {
  it("produces a valid PDF", async () => {
    const pdf = await buildPdf(INPUT);

    expect(Buffer.isBuffer(pdf)).toBe(true);
    expect(pdf.subarray(0, 5).toString()).toBe("%PDF-");
    expect(pdf.length).toBeGreaterThan(1000);
  });

  it("puts the title in the document metadata", async () => {
    const pdf = await buildPdf(INPUT);
    expect(pdf.toString("latin1")).toContain("Billing rewrite sync");
  });

  it("draws the title onto the page, not only into the metadata", async () => {
    const drawn = extractPdfText(await buildPdf(INPUT, { compress: false }));
    expect(drawn).toContain("Billing rewrite sync");
  });

  it("actually draws the version stamp into the page content", async () => {
    // Uncompressed so this asserts on text that was DRAWN, not merely on the
    // version appearing in the document metadata — which is what an earlier
    // version of this test was accidentally matching.
    const drawn = extractPdfText(await buildPdf(INPUT, { compress: false }));

    expect(drawn).toContain("Generated by");
    expect(drawn).toContain(version.version);
    expect(drawn).toContain(version.releaseDate);
  });

  it("draws the minutes content, not just a valid container", async () => {
    const drawn = extractPdfText(await buildPdf(INPUT, { compress: false }));

    expect(drawn).toContain("Ship the billing rewrite on Friday");
    expect(drawn).toContain("Run the migration");
    expect(drawn).toContain("Priya");
    expect(drawn).toContain("we should ship on Friday");
    expect(drawn).toContain("Do we grandfather existing pricing?");
  });

  it("renders a meeting with no minutes", async () => {
    const pdf = await buildPdf({ ...INPUT, minutes: null });
    expect(pdf.subarray(0, 5).toString()).toBe("%PDF-");
  });

  it("renders a meeting with no transcript", async () => {
    const pdf = await buildPdf({ ...INPUT, transcript: [], minutes: null });
    expect(pdf.subarray(0, 5).toString()).toBe("%PDF-");
  });

  it("warns inside the PDF when characters could not be displayed", async () => {
    const pdf = await buildPdf(
      {
        ...INPUT,
        transcript: [{ speakerLabel: "साई राम", text: "会議を始めましょう", sequence: 0 }],
      },
      { compress: false },
    );

    const drawn = extractPdfText(pdf);
    expect(drawn).toContain("could not be displayed");
    expect(drawn).toContain("Markdown");
    // The unsupported text itself must not appear as mojibake.
    expect(drawn).toContain("\u00bf");
  });

  it("adds no such warning when everything is representable", async () => {
    const drawn = extractPdfText(await buildPdf(INPUT, { compress: false }));
    expect(drawn).not.toContain("could not be displayed");
  });
});
